/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UgcReviewRouteImport } from './routes/ugc-review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreativeLibraryRouteImport } from './routes/creative-library'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UgcReviewIndexRouteImport } from './routes/ugc-review.index'
import { Route as CreativeLibraryIndexRouteImport } from './routes/creative-library.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as UgcReviewAssetIdRouteImport } from './routes/ugc-review.$assetId'
import { Route as PerformanceCampaignIdRouteImport } from './routes/performance.$campaignId'
import { Route as CreativeLibraryCreativeIdRouteImport } from './routes/creative-library.$creativeId'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'

const UgcReviewRoute = UgcReviewRouteImport.update({
  id: '/ugc-review',
  path: '/ugc-review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeLibraryRoute = CreativeLibraryRouteImport.update({
  id: '/creative-library',
  path: '/creative-library',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UgcReviewIndexRoute = UgcReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UgcReviewRoute,
} as any)
const CreativeLibraryIndexRoute = CreativeLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreativeLibraryRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const UgcReviewAssetIdRoute = UgcReviewAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => UgcReviewRoute,
} as any)
const PerformanceCampaignIdRoute = PerformanceCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => PerformanceRoute,
} as any)
const CreativeLibraryCreativeIdRoute =
  CreativeLibraryCreativeIdRouteImport.update({
    id: '/$creativeId',
    path: '/$creativeId',
    getParentRoute: () => CreativeLibraryRoute,
  } as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/creative-library': typeof CreativeLibraryRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/performance': typeof PerformanceRouteWithChildren
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/ugc-review': typeof UgcReviewRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/creative-library/$creativeId': typeof CreativeLibraryCreativeIdRoute
  '/performance/$campaignId': typeof PerformanceCampaignIdRoute
  '/ugc-review/$assetId': typeof UgcReviewAssetIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/creative-library/': typeof CreativeLibraryIndexRoute
  '/ugc-review/': typeof UgcReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/performance': typeof PerformanceRouteWithChildren
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/creative-library/$creativeId': typeof CreativeLibraryCreativeIdRoute
  '/performance/$campaignId': typeof PerformanceCampaignIdRoute
  '/ugc-review/$assetId': typeof UgcReviewAssetIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/creative-library': typeof CreativeLibraryIndexRoute
  '/ugc-review': typeof UgcReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/creative-library': typeof CreativeLibraryRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/performance': typeof PerformanceRouteWithChildren
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/ugc-review': typeof UgcReviewRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/creative-library/$creativeId': typeof CreativeLibraryCreativeIdRoute
  '/performance/$campaignId': typeof PerformanceCampaignIdRoute
  '/ugc-review/$assetId': typeof UgcReviewAssetIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/creative-library/': typeof CreativeLibraryIndexRoute
  '/ugc-review/': typeof UgcReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/creative-library'
    | '/dashboard'
    | '/performance'
    | '/products'
    | '/settings'
    | '/ugc-review'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/creative-library/$creativeId'
    | '/performance/$campaignId'
    | '/ugc-review/$assetId'
    | '/campaigns/'
    | '/creative-library/'
    | '/ugc-review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/performance'
    | '/products'
    | '/settings'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/creative-library/$creativeId'
    | '/performance/$campaignId'
    | '/ugc-review/$assetId'
    | '/campaigns'
    | '/creative-library'
    | '/ugc-review'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/creative-library'
    | '/dashboard'
    | '/performance'
    | '/products'
    | '/settings'
    | '/ugc-review'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/creative-library/$creativeId'
    | '/performance/$campaignId'
    | '/ugc-review/$assetId'
    | '/campaigns/'
    | '/creative-library/'
    | '/ugc-review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  CreativeLibraryRoute: typeof CreativeLibraryRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  PerformanceRoute: typeof PerformanceRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  UgcReviewRoute: typeof UgcReviewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ugc-review': {
      id: '/ugc-review'
      path: '/ugc-review'
      fullPath: '/ugc-review'
      preLoaderRoute: typeof UgcReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-library': {
      id: '/creative-library'
      path: '/creative-library'
      fullPath: '/creative-library'
      preLoaderRoute: typeof CreativeLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ugc-review/': {
      id: '/ugc-review/'
      path: '/'
      fullPath: '/ugc-review/'
      preLoaderRoute: typeof UgcReviewIndexRouteImport
      parentRoute: typeof UgcReviewRoute
    }
    '/creative-library/': {
      id: '/creative-library/'
      path: '/'
      fullPath: '/creative-library/'
      preLoaderRoute: typeof CreativeLibraryIndexRouteImport
      parentRoute: typeof CreativeLibraryRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/ugc-review/$assetId': {
      id: '/ugc-review/$assetId'
      path: '/$assetId'
      fullPath: '/ugc-review/$assetId'
      preLoaderRoute: typeof UgcReviewAssetIdRouteImport
      parentRoute: typeof UgcReviewRoute
    }
    '/performance/$campaignId': {
      id: '/performance/$campaignId'
      path: '/$campaignId'
      fullPath: '/performance/$campaignId'
      preLoaderRoute: typeof PerformanceCampaignIdRouteImport
      parentRoute: typeof PerformanceRoute
    }
    '/creative-library/$creativeId': {
      id: '/creative-library/$creativeId'
      path: '/$creativeId'
      fullPath: '/creative-library/$creativeId'
      preLoaderRoute: typeof CreativeLibraryCreativeIdRouteImport
      parentRoute: typeof CreativeLibraryRoute
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface CreativeLibraryRouteChildren {
  CreativeLibraryCreativeIdRoute: typeof CreativeLibraryCreativeIdRoute
  CreativeLibraryIndexRoute: typeof CreativeLibraryIndexRoute
}

const CreativeLibraryRouteChildren: CreativeLibraryRouteChildren = {
  CreativeLibraryCreativeIdRoute: CreativeLibraryCreativeIdRoute,
  CreativeLibraryIndexRoute: CreativeLibraryIndexRoute,
}

const CreativeLibraryRouteWithChildren = CreativeLibraryRoute._addFileChildren(
  CreativeLibraryRouteChildren,
)

interface PerformanceRouteChildren {
  PerformanceCampaignIdRoute: typeof PerformanceCampaignIdRoute
}

const PerformanceRouteChildren: PerformanceRouteChildren = {
  PerformanceCampaignIdRoute: PerformanceCampaignIdRoute,
}

const PerformanceRouteWithChildren = PerformanceRoute._addFileChildren(
  PerformanceRouteChildren,
)

interface UgcReviewRouteChildren {
  UgcReviewAssetIdRoute: typeof UgcReviewAssetIdRoute
  UgcReviewIndexRoute: typeof UgcReviewIndexRoute
}

const UgcReviewRouteChildren: UgcReviewRouteChildren = {
  UgcReviewAssetIdRoute: UgcReviewAssetIdRoute,
  UgcReviewIndexRoute: UgcReviewIndexRoute,
}

const UgcReviewRouteWithChildren = UgcReviewRoute._addFileChildren(
  UgcReviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  CreativeLibraryRoute: CreativeLibraryRouteWithChildren,
  DashboardRoute: DashboardRoute,
  PerformanceRoute: PerformanceRouteWithChildren,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  UgcReviewRoute: UgcReviewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
